### ISSUE TITLE
Leaving a game sometimes does not trigger a "Game joined or ended"

### ISSUE THREAD

**Issue by StarGate01** [StarGate01/AmongUs-Mumble#22]
**Description**
Leaving a game often also does not trigger a "Game joined or ended"

**Steps To Reproduce**
Leave a game? How exactly?

**Expected behavior**
The console prints "Game joined or ended"

**Game version**
Please specify in comments

**Comment by alisenai** [comment]
Description
Leaving a game often does not trigger a "Game joined or ended".

Steps To Reproduce
1) Create a lobby
2) Leave the lobby / Exit to the main menu
3) At this point, no event is fired and the old position is saved

Expected behavior
The console prints "Game joined or ended" and your position is updated accordingly.

Game version
`2020.10.22s`
